### ISSUE TITLE
Support for iOS 8.0?

### ISSUE THREAD

**Issue by stevemoser** [evanspa/PESimu-Select#1]
Could you lower the minimum deployment target to 8.0? My client has 8.0 as their MDT. Is there anything in here that relies on 8.3?

**Comment by evanspa** [comment]
Shouldn't be a problem.

**Comment by stevemoser** [comment]
:+1:

**Comment by evanspa** [comment]
Should be all set now.  Version 1.0.4 supports 8.0 target.  FYI, its dependencies, PEObj-Commons and PEWire-Control were also updated to support 8.0.
